@startuml
cloud {
    [UserDocs]
    [UserDocs] -right-> () api
  }

  package "browser" {
    () hooks
    () ui
    [UserDocs] <-down-> [UserDocs Client]
    hooks <-up-> [UserDocs Client]
    ui <-up-> [UserDocs Client]
  }

  package "localhost" {
    hooks <-down-> [Desktop]
    [Desktop] <-left-> [Chrome]
  }


  package "container" {
    () api <-down-> [Runner]
    [Runner] <-left-> [Test]
    [Runner] <-down-> [Headless Chrome]
    [Test] <-down-> [Headless Chrome]
  }


  ui <-left-> [User]
  [User] <-down-> Chrome
  [User]
  Chrome <-down-> [LAN Device]
  Chrome <-down-> [WAN Device]
  [Headless Chrome] <-down-> [LAN Device]
  [Headless Chrome] <-down-> [WAN Device]
@enduml